/*
===============================================================================
Distribution & Aggregation Review
===============================================================================
Objective:
    This script summarizes numerical data and organizes results across selected
    dimensions to better understand value distribution across categories.

SQL Operations Applied:
    - Aggregations: SUM(), COUNT(), AVG()
    - GROUP BY
    - ORDER BY
===============================================================================
*/
-- Calculate the total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Calculate the total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Calculate the total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Calculate the average costs in each category
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- Calculate the total revenue generated for each category
SELECT 
pr.category,
SUM(ft.sales_amount) As total_revenue
FROM gold.fact_sales ft
LEFT JOIN  gold.dim_products pr
ON pr.product_key = ft.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC;

-- Calculate the total revenue is generated by each customer
SELECT 
cu.customer_key,
cu.first_name,
cu.last_name,
SUM(ft.sales_amount) As total_revenue
FROM gold.fact_sales ft
LEFT JOIN  gold.dim_customers cu
ON cu.customer_key = ft.customer_key
GROUP BY 
cu.customer_key,
cu.first_name,
cu.last_name
ORDER BY total_revenue DESC;

-- Calculate is the distribution of sold items across countries
SELECT 
cu.country,
SUM(ft.quantity) As total_sold_items
FROM gold.fact_sales ft
LEFT JOIN  gold.dim_customers cu
ON cu.customer_key = ft.customer_key
GROUP BY 
cu.country
ORDER BY total_sold_items DESC;
